00
 

                       0fInstaller Boot Options07

 -  To disable pcmcia probing, type: 04nopcmcia <ENTER>07.  

 -  To disable usb probing, type: 04nousb <ENTER>07.  

 -  To disbale pcmcia probing and usb probing, 
    type: 04nousborpcmcia <ENTER>07.  

 -  To enable dma support, type: 04dma <ENTER>07.

 -  To run an unattended installation, type 04unattended <ENTER>07.

 -  To test the memory in your system type: 04memtest <ENTER>07.












0f[F1-Main] [F2-Options]07
