%tr = ( 
%tr,

'guardian' => 'Koruyucu',
'guardian block a host' => 'Ana bilgisayarı engelle',
'guardian block httpd brute-force' => 'httpd kaba kuvvet algılama',
'guardian block owncloud brute-force' => 'Owncloud kaba kuvvet algılama',
'guardian block ssh brute-force' => 'SSH kaba kuvvet algılama',
'guardian blockcount' => 'Vurgu eşiği',
'guardian blocked hosts' => 'Şu anda engellenen ana makineler',
'guardian blocking of this address is not allowed' => 'Verilen adresin engellenmesine izin verilmiyor.',
'guardian blocktime' => 'Engelleme zamanı (saniye)',
'guardian common settings' => 'Ortak ayarlar',
'guardian configuration' => 'Koruyucu yapılandırması',
'guardian daemon' => 'Artalan süreç',
'guardian empty input' => 'Boş giriş: Lütfen geçerli bir ana bilgisayar adresi veya alt ağ girin.',
'guardian enabled' => 'Koruyucuyu aktifleştir',
'guardian firewallaction' => 'Güvenlik duvarı eylemi',
'guardian ignored hosts' => 'Yok sayılan sunucular',
'guardian invalid address or subnet' => 'Geçersiz ana makine adresi veya alt ağ.',
'guardian invalid blockcount' => 'Geçersiz Engelleme Sayısı: Lütfen sıfırdan daha büyük bir doğal sayı girin.',
'guardian invalid blocktime' => 'Geçersiz Engelleme Zamanı: Lütfen sıfırdan daha büyük bir doğal sayı girin.',
'guardian invalid logfile' => 'Günlük dosyası için sağlanan yol geçerli değil.',
'guardian logfacility' => 'Günlük tesisi',
'guardian logfile' => 'Günlük dosyası',
'guardian loglevel' => 'Günlük seviyesi',
'guardian loglevel_off' => 'Kapalı',
'guardian loglevel_info' => 'Bilgi',
'guardian loglevel_debug' => 'Düzeltme',
'guardian logtarget_syslog' => 'Sistem günlüğü',
'guardian logtarget_file' => 'Dosya',
'guardian logtarget_console' => 'Konsol',
'guardian no entries' => 'Şu anda hiçbir kayıt bulunamadı.',
'guardian not running no hosts can be blocked' => 'Koruyucu çalışmıyor. Hiçbir ana makine engellenmeyecek.',
'guardian priolevel_high' => '1 - Yüksek',
'guardian priolevel_medium' => '2 - Orta',
'guardian priolevel_low' => '3 - Düşük',
'guardian priolevel_very_low' => '4 - Çok düşük',
'guardian service' => 'Koruyucu servisi',

);

#EOF
