#!/bin/sh
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2007-2022  IPFire Team  <info@ipfire.org>                     #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

. /etc/sysconfig/rc
. ${rc_functions}

LENGTH=40

play () {

	beep -l $LENGTH -f $1 2> /dev/null

}

case "${1}" in
	start)
		for i in 440 466 494 523 554 587 622 659 698 740 764 831 880; do
			play $i
		done

		;;

	stop)
		for i in 880 831 764 740 698 659 622 587 554 532 494 466 440; do
			play $i
		done
		;;

	up)
		for i in 440 622 880; do
			play $i
		done
		;;

	down)
		for i in 880 622 440; do
			play $i
		done
		;;

	*)
		echo "Usage: ${0} {start|stop|up|down}"
		exit 1
		;;
esac
