#!/bin/sh
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2007-2022  IPFire Team  <info@ipfire.org>                     #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

. /etc/sysconfig/rc
. ${rc_functions}

CONFIG_FILE="/var/ipfire/dhcp/relay"

if [ -r "${CONFIG_FILE}" ]; then
	eval $(/usr/local/bin/readhash ${CONFIG_FILE})
fi

ARGS="-q"

for interface in ${INTERFACES}; do
	ARGS="${ARGS} -i ${interface}"
done

ARGS="${ARGS} ${SERVERS}"

case "${1}" in
	start)
		boot_mesg "Starting DHCP Relay..."
		loadproc /usr/sbin/dhcrelay ${ARGS}
		;;

	stop)
		boot_mesg "Stopping DHCP Relay..."
		killproc -p /var/run/dhcrelay.pid /usr/sbin/dhcrelay
		;;

	restart)
		${0} stop
		sleep 1
		${0} start
		;;

	status)
		statusproc /usr/sbin/dhcrelay
		;;

	*)
		echo "Usage: ${0} {start|stop|restart|status}"
		exit 1
		;;
esac
