#!/bin/sh
########################################################################
# Begin $rc_base/init.d/mountkernfs
#
# Description : Mount proc and sysfs
#
# Authors     : Gerard Beekmans - gerard@linuxfromscratch.org
#
# Version     : 00.00
#
# Notes       :
#
########################################################################

. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
	start)
		boot_mesg -n "Mounting kernel-based file systems:" ${INFO}

		if ! mountpoint /proc &> /dev/null; then
			boot_mesg -n " /proc" ${NORMAL}
			mount -n -t proc /proc /proc || failed=1
		fi

		if ! mountpoint /sys &> /dev/null; then
			boot_mesg -n " /sys" ${NORMAL}
			mount -n -t sysfs /sys /sys || failed=1
		fi

		if ! mountpoint /run &> /dev/null; then
			boot_mesg -n " /run" ${NORMAL}
			mount -n -t tmpfs -o nosuid,nodev,mode=755,size=8M /run /run || failed=1
		fi

		if ! mountpoint /sys/fs/cgroup &> /dev/null; then
			boot_mesg -n " /sys/fs/cgroup" ${NORMAL}
			mount -t cgroup2 none /sys/fs/cgroup || failed=1
		fi

		if ! mountpoint /sys/firmware/efi/efivars &>/dev/null && [ -d "/sys/firmware/efi" ]; then
			boot_mesg -n " /sys/firmware/efi/efivars" ${NORMAL}
			mount -t efivarfs efivarfs /sys/firmware/efi/efivars || failed=1
		fi

		# create folder for dhcpcd changeroot
		mkdir -p /run/dhcpcd/chroot
		chown dhcpcd:dhcpcd /run/dhcpcd/chroot
		chmod 750 /run/dhcpcd/chroot

		boot_mesg "" ${NORMAL}

		(exit ${failed})
		evaluate_retval
		;;

	*)
		echo "Usage: ${0} {start}"
		exit 1
		;;
esac

# End $rc_base/init.d/mountkernfs
