#!/bin/sh
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2007-2022  IPFire Team  <info@ipfire.org>                     #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
	start)
		boot_mesg -n "Mounting ramdisk file systems:" ${INFO}

		if ! mountpoint /var/lock &>/dev/null; then
			boot_mesg -n " /var/lock" ${NORMAL}
			mount -n -t tmpfs -o nosuid,nodev,size=8M /var/lock /var/lock || failed=1
		fi

		boot_mesg "" ${NORMAL}

		(exit ${failed})
		evaluate_retval
		;;

	*)
		echo "Usage: ${0} {start}"
		exit 1
		;;
esac
