#!/bin/sh
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2007-2022  IPFire Team  <info@ipfire.org>                     #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

. /etc/sysconfig/rc
. ${rc_functions}

check_drives () {
	drives_ready="1";
	for drive in $drives; do
		if [ `blkid | grep $drive | wc -l` == 0 ]; then
			drives_ready="0";
		fi
	done
}

case "${1}" in
	start)
		drives=`grep "^UUID=" /etc/fstab | cut -f1 | cut -d" " -f1 | cut -d"=" -f2`;

		check_drives;
		if [ "$drives_ready" == "0" ]; then
			boot_mesg -n "Wait for devices used in fstab "
			for (( i=1; i<30; i++)) do
				check_drives;
				if [ "$drives_ready" == "1" ]; then
					break;
				fi
				boot_mesg -n "."
				sleep 1
			done
		fi
		exit 0;
		;;
	*)
		echo "Usage: ${0} {start}"
		exit 1
		;;
esac
