#!/bin/sh
# Clear screen
/usr/bin/clear
echo "Shutting down..."
echo "Sending all processes the TERM signal..."
/sbin/killall5 -15
sleep 3
echo "Sending all processes the KILL signal..."
/sbin/killall5 -9
sleep 3
echo "Unmounting filesystems"
/bin/umount /tmp
/bin/umount /sys
/bin/umount /dev/pts
/bin/umount /dev
/bin/umount /root
/bin/umount /proc
echo "Unmounting root"
/bin/mount -n -o remount,ro /
/sbin/reboot -f
