# Romanian  (ro) Data File 
#
# This file is part of the IPCop Firewall.
# 
# IPCop is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# IPCop is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with IPCop; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
# 
# (c) The SmoothWall Team
# 
# IPCop translation
# (c) 2004 Viorel Melinte
#  
#

%tr = ( 
%tr, 
 
'a ca certificate with this name already exists' => 'Există deja un Certificat CA cu acest nume.', 
'a connection with this common name already exists' => 'Există deja o conexiune cu acest nume uzual.', 
'a connection with this name already exists' => 'Există deja o conexiune cu acest nume.', 
'access allowed' => 'Acces permis de la:', 
'action' => 'Acţiune', 
'add' => 'Adauga', 
'add a host' => 'Adauga o gazda:', 
'add a new rule' => 'Adauga o regula noua:', 
'add network' => 'Adaugă reţea', 
'add new alias' => 'Adauga alias nou:', 
'add new lease' => 'Adauga inchiriere noua fixa:', 
'add service' => 'Adaugă serviciu', 
'add xtaccess' => 'Adauga acces extern', 
'admin user password has been changed' => 'Parola utilizatorului admin a fost schimbata', 
'administrator user password' => 'Parola administratorului', 
'adsl settings' => 'Setări ADSL', 
'advanced' => 'Avansat', 
'again' => 'Din nou:', 
'alcatelusb help' => 'Pentru a folosi un modem model Speedtouch 330 sau Speedtouch USB trebuie să aduceţi microcodul pe sistemul IPCop. Vă rugăm să faceţi download la pachetul de <b>Microcod Integrat</b> pentru SpeedTouch 330 de la speedtouch.com, despachetaţi arhiva cu unzip şi încărcaţi fişierul corespunzător modelului de modem: RQD6_3.xxx pentru Rev<4 sau ZZZL_3.xxx pentru Rev=4 folosind formularul de mai jos.', 
'alcatelusb upload' => 'Încarcă fişierul de Speedtouch USB', 
'alias ip' => 'IP alias', 
'aliases' => 'Alias-uri', 
'aliases not active' => 'Alias-urile nu vor fi active pana cand interfata RED nu va avea IP static.', 
'all updates installed' => 'Toate actualizarile sunt instalate.', 
'alt dialup' => 'Formeaza numar.', 
'alt home' => 'Acasa', 
'alt information' => 'Informatii', 
'alt logs' => 'Log-uri', 
'alt services' => 'Servicii', 
'alt system' => 'Sistem', 
'alt vpn' => 'Vpn-uri', 
'ansi t1.483' => 'ANSI T1.483', 
'april' => 'Aprilie', 
'archive not exist' => 'Arhiva de configurare nu există', 
'are you sure' => 'Sunteţi sigur?', 
'arp table entries' => 'Inregistrari tabel ARP:', 
'august' => 'August', 
'authentication' => 'Autentificare:', 
'automatic' => 'Automat', 
'available updates' => 'Actualizari valabile:', 
'average' => 'Valoarea medie', 
'back' => 'Inapoi', 
'backup' => 'Backup', 
'backup config floppy' => 'Disc floppy de rezervă a configurării', 
'backup configuration' => 'Configurare backup:', 
'backup sets' => 'Seturi de rezervă', 
'backup to floppy' => 'Salvează pe floppy ca rezervă', 
'backupprofile' => 'În cazul în care reconectarea eşuează, treceţi pe profilul ', 
'bad characters in script field' => 'Caractere incorecte in campul de scriere.', 
'bad characters in the telephone number field' => 'Caractere incorecte in campul numarului de telefon.', 
'bad destination range' => 'Prima valoare a intervalului de porturi este egala sau mai mare decat valoarea secundara.', 
'bad ignore filter' => 'Filtru de ignorare eronat:', 
'bad return code' => 'Programul de ajutor a returnat codul de eroare', 
'bad source range' => 'Intervalul sursa are prima valoare mai mare sau egala cu valoarea secundara.', 
'behind a proxy' => 'In spatele unui proxy', 
'bewan adsl pci st' => 'Bewan ADSL PCI ST', 
'bewan adsl usb' => 'Bewan ADSL USB', 
'blue' => 'ALBASTRU', 
'blue access' => 'Acces pe Albastru', 
'blue interface' => 'Interfaţa Albastră', 
'broadcast' => 'Transmisie', 
'broken pipe' => 'Flux întrerupt', 
'buffered memory' => 'Memorie Tampon', 
'buffers' => 'tampoane de date', 
'bytes per second' => 'Octeţi pe Secundă', 
'ca certificate' => 'Certificat CA', 
'ca name' => 'Numele CA', 
'cache management' => 'Administrarea rezervei de date', 
'cache size' => 'Mărimea rezervei de date (MB):', 
'cached' => 'rezervat', 
'cached memory' => 'Memoria Tampon', 
'cancel' => 'Anulează', 
'cannot enable both nat traversal and compression' => 'Nu se pot activa simultan NAT Transversal şi Compresia', 
'cannot enable ntp without specifying primary' => 'Nu puteţi activa NTP-ul fără precizarea NTP-ului primar.', 
'cannot specify secondary dns without specifying primary' => 'Nu puteti specifica dns-ul secundar fara a specifica dns-ul primar.', 
'cannot specify secondary ntp without specifying primary' => 'Nu puteti specifica NTP-ul secundar fara a specifica NTP-ul primar', 
'cant enable xtaccess' => 'Daca regula de forwarding este dezactivata atunci nu puteti activa accesul extern pentru aceasta regula.', 
'caps all' => 'TOT', 
'capsclosed' => 'INCHIS', 
'capsopen' => 'DESCHIDE', 
'capswarning' => 'AVERTIZARE', 
'cfg restart' => 'O restartare este sugerată după restaurarea unei arhive de configurare', 
'chain' => 'Lanţ', 
'change passwords' => 'Schimba parola', 
'check vpn lr' => 'Verifica', 
'city' => 'Oraş', 
'clear cache' => 'Curăţă rezerva de date', 
'clenabled' => 'Activează sincronizarea clienţilor', 
'click to disable' => 'Activat (click ca să dezactivezi)', 
'click to enable' => 'Dezactivat (click ca să activezi)', 
'clock has not been synchronized' => 'Ceasul nu a fost sincronizat', 
'clock last synchronized at' => 'Ceasul a fost ultima dată sincronizat la', 
'common name' => 'Nume Uzual', 
'compression' => 'Compresie:', 
'computer to modem rate' => 'Rata de transfer calculator - modem:', 
'concentrator name' => 'Numele concentratorului:', 
'confirmation' => 'confirmare', 
'connect on ipcop restart' => 'Conectare dupa restartare IpCop', 
'connect timeout' => 'Timp conexiune expirat:', 
'connected' => 'Conectat', 
'connecting' => 'Se conecteaza...', 
'connection' => 'Conexiune', 
'connection tracking' => 'Urmărirea conexiunilor IPTables', 
'connections' => 'Conexiuni', 
'could not be opened' => 'nu poate fi deschisa', 
'could not connect to' => 'Nu m-am putut conecta la', 
'could not connect to www ipcop org' => 'Nu ma pot conecta la www.ipcop.org', 
'could not create directory' => 'Nu pot creea directorul.', 
'could not download latest patch list' => 'Nu pot descarca ultima lista (nu sunt conectat).', 
'could not download latest updates' => 'N-am putut descărca ultimele actualizări.', 
'could not download the available updates list' => 'Nu pot descarca lista valabila de actualizari.', 
'could not open available updates file' => 'Nu pot deschide fisierul cu actualizarile valabile.', 
'could not open installed updates file' => 'Nu pot deschide fisierul actulizat instalat', 
'could not open update information file' => 'Nu pot deschide fisierul cu informatii despre actualizare', 
'create' => 'Crează', 
'credits' => 'Credite', 
'cron server' => 'Server CRON', 
'current aliases' => 'Aliasuri curente', 
'current dynamic leases' => 'Inchirieri dinamice curente', 
'current fixed leases' => 'Inchirieri fixe curente', 
'current hosts' => 'Gazde curente:', 
'current profile' => 'Profil curent:', 
'current rules' => 'Reguli curente:', 
'custom networks' => 'Reţele individuale', 
'custom services' => 'Servicii individuale', 
'dat without key' => 'O arhivă încriptată nu poate fi restaurată fără cheie.', 
'date' => 'Data', 
'date not in logs' => 'Nu exista inregistrari (sau doar partiale) pentru ziua dorita.', 
'day' => 'Ziua', 
'days' => 'zile', 
'ddns hostname added' => 'Adaugare nume gazda - dinamic DNS', 
'ddns hostname removed' => 'Stergere nume gazda - dinamic DNS', 
'december' => 'Decembrie', 
'default lease time' => 'Timp inchiriere initial (minute):', 
'default networks' => 'Reţele implicite', 
'default renewal time' => 'Timp de reînnoire implicit', 
'default services' => 'Servicii implicite', 
'delete' => 'Sterge', 
'demon login script' => 'Script logare Demon', 
'description' => 'Descriere', 
'dest ip and port' => 'IP destinatie:Port', 
'destination' => 'Destinatie', 
'destination ip' => 'IP destinatie', 
'destination ip bad' => 'IP destinatie incorect', 
'destination port' => 'Port destinatie', 
'destination port numbers' => 'Portul destinatie trebuie sa fie un numar sau un interval de numere corecte.', 
'destination port overlaps' => 'Intervalul porturilor destinatie se suprapun cu un interval de porturi existent.', 
'detail level' => 'Nivel de detalii', 
'device' => 'Dispozitiv', 
'dhcp configuration' => 'Configurare DHCP', 
'dhcp mode' => 'Mod DHCP', 
'dhcp server' => 'Server DHCP', 
'dhcp server disabled' => 'Serverul DHCP este dezactivat. Oprit.', 
'dhcp server disabled on blue interface' => 'server DHCP dezactivat pentru interfaţa ALBASTRĂ', 
'dhcp server enabled' => 'Serverul DHCP activat. Repornit.', 
'dial' => 'Conectează', 
'dial user password' => 'Parola utilizatorului pentru conectarea telefonică:', 
'dial user password has been changed' => 'Parola utilizatorului pentru conectarea telefonică a fost schimbată.', 
'dialing mode' => 'Mod de conectare telefonică:', 
'dialup settings' => 'Setări de conectare telefonică', 
'disk usage' => 'Utilizare de disc:', 
'dmz' => 'ZDM', 
'dmz pinhole configuration' => 'Configurarea orificiilor ZDM', 
'dmz pinhole rule added' => 'Adăugat regulă de orificiu de ZDM; restartez orificiul de ZDM', 
'dmz pinhole rule removed' => 'Eliminat regulă de orificiu de ZDM; restartez orificiul de ZDM', 
'dns check failed' => 'Verificarea DNS a eşuat', 
'dns proxy server' => 'Server proxy DNS', 
'dod' => 'Conectează telefonic la cerere', 
'dod for dns' => 'Conectează telefonic la cerere pentru DNS:', 
'dod waiting' => 'Conectarea telefonică în progres', 
'domain' => 'Domeniu', 
'domain name' => 'Nume de domeniu', 
'domain name suffix' => 'Sufixul numelui de domeniu:', 
'domain not set' => 'Domeniul nu este setat.', 
'downlink speed' => 'Viteza de descărcare (kbit/sec)', 
'download new ruleset' => 'Descarcă un set de reguli noi', 
'driver' => 'Driver', 
'dst port' => 'Port de destinaţie', 
'dstprt range overlaps' => 'Portul de destinaţie se suprapune cu un port deja definit.', 
'dstprt within existing' => 'Portul de destinaţie se află într-un interval de porturi deja definit.', 
'duplicate ip' => 'A fost introdusă o adresă de IP deja existentă', 
'duplicate mac' => 'A fost introdusă o adresă de MAC deja existentă', 
'duplicate name' => 'Numele introdus e deja folosit. Vă rugăm să alegeţi un alt nume.', 
'dynamic dns' => 'DNS dinamic', 
'dynamic dns client' => 'Client de DNS dinamic', 
'e-mail address too long' => 'Adresa e-mail este prea lungă; nu poate să aibă mai mult de 40 de caractere.', 
'eciadsl help' => 'Pentru a folosi modemul de ECI ADSL trebuie să încărcaţi fişierul synch.bin pe serverul de IPCOP. Vă rugăm să descărcaţi fişierul de pe site-ul ECIADSL, apoi să încărcaţi fişierul <B>synch.bin</B> folosind câmpurile de mai jos.', 
'eciadsl upload' => 'Încărcaţi fişierul synch.bin pentru ECI ADSL', 
'edit' => 'Modifică', 
'edit a rule' => 'Modifică o regulă existentă:', 
'edit hosts' => 'Modifică gazdele', 
'edit network' => 'Modifică reţeaua', 
'edit service' => 'Modifică serviciul', 
'empty' => 'Gol', 
'enable ignore filter' => 'Activează filtrul de ignorare', 
'enable javascript' => 'Activează JavaScript', 
'enable wildcards' => 'Activează şabloane:', 
'enabled' => 'Activat:', 
'enabled on' => 'Activat la', 
'enabledtitle' => 'Activat', 
'encapsulation' => 'Încapsulare', 
'encrypted' => 'Încriptat', 
'end address' => 'Adresă de sfârşit:', 
'err bk 1' => 'Eroare în crearea arhivei', 
'err bk 2 key' => 'Eroare în crearea fişierului cheie', 
'err bk 3 tar' => 'Eroare în adăugarea fişierelor la arhivă', 
'err bk 4 gz' => 'Eroare în comprimarea arhivei', 
'err bk 5 encrypt' => 'Eroare în încriptarea arhivei', 
'err rs 1' => 'Eroare în restaurarea arhivei', 
'err rs 6 decrypt' => 'Eroare în decriptarea arhivei', 
'err rs 7 untartst' => 'Arhivă decriptată invalidă', 
'err rs 8 untar' => 'Eroare în dezarhivarea arhivei', 
'error messages' => 'Mesaje de eroare', 
'every' => 'Fiecare', 
'excluding buffers and cache' => '-/+ tampoane/rezervă de date', 
'expected' => 'Expectat', 
'expires' => 'Expira', 
'export' => 'Exporta', 
'external access' => 'Acces extern', 
'external access configuration' => 'Configurare acces extern', 
'external access rule added' => 'Adăugat regulă de acces extern; controler-ul de acces este restartat', 
'external access rule removed' => 'Eliminat regulă de acces extern; controler-ul de acces este restartat.', 
'external aliases configuration' => 'Configurare de alias-uri externe', 
'february' => 'februarie', 
'filename' => 'Nume de fişier', 
'filesystem full' => 'Fişier de sistem plin', 
'firewall' => 'Firewall', 
'firewall hits' => 'Numărul total de conexiuni pe firewall pentru', 
'firewall log' => 'Arhiva de firewall', 
'firewall log viewer' => 'Vizualizator al arhivei de firewall', 
'firewall logs' => 'Arhive de firewall', 
'firmware' => 'Arhivă', 
'firmware upload' => 'Înarcă arhivă/drivere', 
'fixed ip lease added' => 'Adăugat lease de IP fix', 
'fixed ip lease removed' => 'Eliminat lease de IP fix', 
'force update' => 'Forţează actualizare', 
'forwarding rule added' => 'Adăugat regulă de expediere; expeditorul este restartat', 
'forwarding rule removed' => 'Eliminat regulă de expediere; expeditorul este restartat', 
'forwarding rule updated' => 'Actualizat regulă de expediere; expeditorul este restartat', 
'free' => 'Liber', 
'g.dtm' => 'G.dmt', 
'hours' => 'ore', 
'not present' => '<B>Nu-i</B> prezent', 
'present' => 'Prezent', 
'unknown' => 'NECUNOSCUT', 
'vpn' => 'VPN', 
'year' => 'Anul', 
 
); 
 