# Lithuanian (lt) Data File 
#
# This file is part of the IPCop Firewall.
# 
# IPCop is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# IPCop is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with IPCop; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
# 
# (c) The SmoothWall Team
# 
# IPCop translation
# (c) 2004 Rodion Kotelnikov
# (c) 2005 Aurimas Fišeras 
#

%tr = ( 
%tr, 
 
'action' => 'veiksmas', 
'add' => 'pridėti', 
'add a new rule' => 'pridėti naują taisyklę:', 
'administrator user password' => 'naudotojo admin slaptažodis:', 
'adsl settings' => 'ADSL nustatymai', 
'again' => 'Dar kartą', 
'aliases' => 'Aliasai', 
'all interfaces' => 'Visos sąsajos', 
'alt dialup' => 'Prisijungimas', 
'alt services' => 'Servisai', 
'alt system' => 'Sistema', 
'alt vpn' => 'VPT', 
'april' => 'Balandis', 
'archive not exist' => 'Nustatymų archyvas neegzistuoja', 
'are you sure' => 'Esate įsitikinę?', 
'arp table entries' => 'ARP lentelės įrašai:', 
'august' => 'Rugpjūtis', 
'back' => 'ATGAL', 
'backup' => 'Atsarginė kopija', 
'backup config floppy' => 'Išsaugoti nustatymus - Į diskelį', 
'backup configuration' => 'Išsaugoti nustatymus:', 
'backup sets' => 'Archyvų rinkiniai', 
'backup to floppy' => 'Išsaugoti į diskelį', 
'blue' => 'MĖLYNAS', 
'cancel' => 'Atsisakyti', 
'cfg restart' => 'Rekomenduojama perkrauti sistemą po nustatymų atstatymo.', 
'change passwords' => 'Keisti slaptažodžius', 
'city' => 'Miestas', 
'click to disable' => 'Įjungta (įšjungti - spauskite)', 
'click to enable' => 'Išjungta (įjungti - spauskite)', 
'compression' => 'Glaudinimas:', 
'connected' => 'Prisijungęs', 
'connecting' => 'Jungiamasi...', 
'connection' => 'Prisijungimas', 
'connections' => 'Ryšiai', 
'country' => 'Šalis', 
'create' => 'Sukurti', 
'credits' => 'Kūrėjai', 
'day' => 'Diena', 
'day after' => 'Rytoj', 
'day before' => 'Vakar', 
'days' => 'Dienos', 
'december' => 'Gruodis', 
'dhcp server' => 'DHCP serveris', 
'dial' => 'Prisijungti', 
'driver' => 'Tvarkyklė', 
'dynamic dns' => 'Dinaminis DNS', 
'edit' => 'Redaguoti', 
'edit hosts' => 'Keisti hostus', 
'empty' => 'Tuščias', 
'every' => 'Kiekvienas', 
'export' => 'Eksportuoti', 
'external access' => 'Išorinė prieiga', 
'february' => 'Vasaris', 
'firewall' => 'Ugniasienė', 
'firewall log' => 'Ugniasienės registras', 
'firewall logs' => 'Ugniasienės registrai', 
'free' => 'Laisva', 
'friday' => 'Penktadienis', 
'graph' => 'Grafikas', 
'green' => 'ŽALIAS', 
'gui settings' => 'GVS nustatymai', 
'hangup' => 'Atsijungti', 
'ids logs' => 'AAS žurnalas', 
'import' => 'Importuoti', 
'insert floppy' => 'Jei norite padaryti nustatymų archyvą į diskelį, tai įdėkite suformatuotą diskelį į diskasukį, prijungtą prie IPCop, ir spauskite <i>Išsaugoti į diskelį</i>. Prašome įdėmiai išanalizuoti rezultatą ir įsitikinti, kad archyvas padarytas sėkmingai. Tai gali truputį užtrukti, būkite kantrūs.<p>', 
'installed' => 'Įdiegtas', 
'intrusion detection' => 'Atakų aptikimas', 
'intrusion detection system' => 'Atakų Aptikimo Sistema', 
'intrusion detection system log viewer' => 'Atakų Aptikimo Sistemos žurnalo peržiūra', 
'intrusion detection system2' => 'Atakų Aptikimo Sistema:', 
'invalid broadcast ip' => 'Neteisingas broadcast IP', 
'invalid cache size' => 'Klaidingas kešo dydis.', 
'invalid characters found in pre-shared key' => 'Klaidingi simboliai rasti pre-shared rakte.', 
'invalid date entered' => 'Įvesta klaidinga data.', 
'invalid end address' => 'Klaidingas galinis adresas.', 
'invalid fixed ip address' => 'Klaidingas fiksuotas IP adresas', 
'invalid fixed mac address' => 'Klaidingas fixuotas MAC adresas', 
'invalid input' => 'Klaidinga įvestis', 
'invalid input for authentication method' => 'Klaidinga įvestis atpažinimo metodui.', 
'invalid ip' => 'Klaidingas IP adresas', 
'invalid keep time' => 'Saugojimo laikas turi būti skaičius', 
'invalid key' => 'Klaidingas raktas.', 
'invalid logserver address' => 'Klaidingas syslogd serverio adresas', 
'invalid md5sum' => 'Klaidinga MD5 suma.', 
'invalid start address' => 'Neteisingas pradinis adresas.', 
'invalid time period' => 'Neteisingas laikotarpis', 
'invalid upstream proxy username or password setting' => 'Neteisingas išeinančio tarpinio serverio naudotojo vardas ar slaptažodis.', 
'invalid vpi vpci' => 'Neteisingi VPI/VPCI nustatymai', 
'invalid wins address' => 'Neteisingas WINS serverio adresas', 
'january' => 'Sausis', 
'log settings' => 'Žurnalo nustatymai', 
'log summaries' => 'Žurnalo santraukos', 
'log summary' => 'Žurnalo santrauka', 
'march' => 'Kovas', 
'may' => 'Gegužė', 
'modem' => 'Modemas', 
'monday' => 'Pirmadienis', 
'november' => 'Lapkritis', 
'proxy' => 'Tarpinis serveris', 
'proxy logs' => 'Tarpinio serverio žurnalas', 
'refresh' => 'Atnaujinti', 
'saturday' => 'Šeštadienis', 
'shutdown' => 'Išjungti', 
'ssh access' => 'SSH prieiga', 
'ssnetwork status' => 'Tinklo būklė', 
'sspasswords' => 'Slaptažodžiai', 
'ssport forwarding' => 'Prievadų peradresavimas', 
'ssproxy graphs' => 'Tarpino serverio grafikai', 
'sssystem status' => 'Sistemos būklė', 
'sstraffic graphs' => 'Srauto grafikai', 
'status' => 'Būklė', 
'sunday' => 'Sekmadienis', 
'system graphs' => 'Sistemos grafikai', 
'system logs' => 'Sistemos žurnalas', 
'thursday' => 'Ketvirtadienis', 
'time' => 'Laikas', 
'time server' => 'Laiko serveris', 
'traffic shaping' => 'Srautų valdymas', 
'tuesday' => 'Antradienis', 
'updates' => 'Atnaujinimai', 
'updates is old1' => 'Jūsų atnaujinimo failas yra', 
'updates is old2' => 'd. senumo. Mes rekomenduojame jį atnaujinti puslapyje <b>Sistema>Atnaujinimai</b>.', 
'upload' => 'Išsiuntimas', 
'wednesday' => 'Trečiadienis', 
'wireless' => 'Bevielis', 
'year' => 'Metai', 
'your e-mail' => 'Jūsų el. pašto adresas', 
 
); 
 