#!/bin/bash
export LANG=en_US.utf8
/usr/local/sbin/setup /dev/tty2 INSTALL
echo Restarting udev...
killall udevd
/sbin/udevd --daemon
/sbin/udevadm trigger
/sbin/udevadm settle
rm -f /etc/rc.d/rcsysinit.d/S75firstsetup
