#!/bin/bash
# Edit the serial console entry at /etc/inittab matching to console parameter.
ser_console() {
	while test x"$1" != x
	do
		case $1 in
			console=*)
				scon=${1##console=};
				sed -i -e "s|^7:2345:respawn:/sbin/agetty.*|7:2345:respawn:/sbin/agetty ${scon%%,*} ${scon##*,}|g" /etc/inittab
				shift
			;;
			*)
				shift
			;;
		esac
	done
}
cmdline=`cat /proc/cmdline`
ser_console $cmdline
# reload inittab
/sbin/init q
#
/etc/init.d/sysklogd start
export LANG=en_US.utf8
/usr/local/sbin/setup /dev/tty2 INSTALL
if [ "${?}" == "1" ]; then
	echo Setup not finished. Rebooting ...
	reboot -f
fi
echo Restarting udev...
killall udevd
/sbin/udevd --daemon
/sbin/udevadm trigger
/sbin/udevadm settle
/etc/init.d/sysklogd stop
rm -f /etc/rc.d/rcsysinit.d/S75firstsetup
