#!/bin/sh
########################################################################
# Begin $rc_base/init.d/ipfireseeder
#
# Description : This is a script that starts the torrent-seeder on your
#								local IPFire.
#
# Authors     : Michael Tremer (mitch@ipfire.org)
#
# Version     : 01.00
#
# Notes       :
#
########################################################################

. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
	start)
		boot_mesg "Starting IPFire Seeder..."
		cd /var/log/seeder
		loadproc screen -dmS seeder /usr/bin/rtorrent -o port_range=35700-35705 \
			/var/ipfire/seeder/*.torrent
		if ! grep -q "35700:35705" /var/ipfire/xtaccess/config ; then
			echo "tcp,0.0.0.0/0,35700:35705,on,0.0.0.0,IPFireSeeder" >> /var/ipfire/xtaccess/config
			/usr/local/bin/setxtaccess
		fi
		;;

	stop)
		boot_mesg "Stopping IPFire Seeder..."
		killproc /usr/bin/rtorrent
		;;

	reload)
		boot_mesg "Reloading IPFire Seeder..."
		reloadproc /usr/bin/rtorrent
		;;

	restart)
		${0} stop
		sleep 1
		${0} start
		;;

	status)
		statusproc /usr/bin/rtorrent
		;;

	*)
		echo "Usage: ${0} {start|stop|reload|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/ipfireseeder
