#!/bin/sh
########################################################################
# Begin $rc_base/init.d/mldonkey
#
# Description : Mldonkey Init Script
#
# Authors     : Michael Tremer (ms@ipfire.org)
#
# Version     : 01.00
#
# Notes       :
#
########################################################################

. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
	start)
		boot_mesg "Starting mldonkey..."
		chown mldonkey.mldonkey /opt/mldonkey -R &>/dev/null
		rm -f /opt/mldonkey/.mldonkey/*tmp* 2>/dev/null
		HOME=/opt/mldonkey /opt/mldonkey/mlnet >/dev/null 2>&1 &
		evaluate_retval
		;;

	stop)
		boot_mesg "Stopping mldonkey..."
		killproc /opt/mldonkey/mlnet
		;;

	restart)
		${0} stop
		sleep 1
		${0} start
		;;

	status)
		statusproc /opt/mldonkey/mlnet
		;;

	*)
		echo "Usage: ${0} {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/mldonkey
