#!/bin/sh
# Begin $rc_base/init.d/ntp

. /etc/sysconfig/rc
. $rc_functions

eval $(/usr/local/bin/readhash /var/ipfire/time/settings)

case "$1" in
	start)
		if [ "$ENABLESETONBOOT" == "on" ]; then
			boot_mesg -n "Setting time on boot..."
			pidof wpa_supplicant dhcpcd 2>&1 > /dev/null
			if [ "${?}" == "0" ]; then
				if [ ! -e /var/ipfire/red/active ]; then
					boot_mesg ""
					boot_mesg -n "Waiting for red connection"
					for (( i=30; i>1; i-- )) do
						if [ -e /var/ipfire/red/active ]; then
							break;
						fi
						boot_mesg -n "."
						sleep 2
					done
					sleep 5
				fi
			fi
			if [ -e /var/ipfire/red/active ]; then
				boot_mesg ""
				loadproc /usr/local/bin/settime $(cat /var/ipfire/time/settime.conf)
			else
				boot_mesg " ERROR! Not online!"
				echo_warning
			fi
		fi

		boot_mesg "Starting ntpd..."
		loadproc /usr/bin/ntpd -Ap /var/run/ntpd.pid
		;;

	stop)
		boot_mesg "Stopping ntpd..."
		killproc /usr/bin/ntpd
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		statusproc /usr/bin/ntpd
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/ntp
