#!/bin/sh
# Begin $rc_base/init.d/sshd

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

#$LastChangedBy: bdubbs $
#$Date: 2006-04-15 17:34:16 -0500 (Sat, 15 Apr 2006) $

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
    start)
        boot_mesg "Starting SSH Server..."
        # Also prevent ssh from being killed by out of memory conditions
        loadproc /usr/sbin/sshd 
        sleep 1
        echo "-16" >/proc/`cat /var/run/sshd.pid`/oom_adj
        ;;

    stop)
        boot_mesg "Stopping SSH Server..."
        killproc /usr/sbin/sshd
        ;;

    reload)
        boot_mesg "Reloading SSH Server..."
        reloadproc /usr/sbin/sshd
        ;;

    restart)
        $0 stop
        sleep 1
        $0 start
        ;;

    status)
        statusproc /usr/sbin/sshd
        ;;

    *)
        echo "Usage: $0 {start|stop|reload|restart|status}"
        exit 1
        ;;
esac

# End $rc_base/init.d/sshd
