#!/bin/sh
########################################################################
# Begin $rc_base/init.d/teamspeak
#
# Description :	Start/Stops the teamspeak server
#
# Authors     : Michael Tremer
#
# Version     : 01.00
#
# Notes       :
#
########################################################################

export LANG=en_US.utf8
cd /opt/teamspeak && sudo -u teamspeak ./teamspeak2-server_startscript $*
exit 0
# End $rc_base/init.d/teamspeak
