#!/bin/sh
########################################################################
# Begin $rc_base/init.d/tvheadend
#
# Description : This is a script that starts tvheadend as deamon
#
# Authors     :
#
# Version     :
#
# Notes       :
#
########################################################################

. /etc/sysconfig/rc
. $rc_functions

PIDFILE=/var/run/tvheadend.pid

case "$1" in
        start)
				if [ -e "$PIDFILE" ]
				then
					if /bin/ps p `cat $PIDFILE` | grep tvheadend >/dev/null;
					then
						boot_mesg "tvheadend already running!" ${WARNING}
						echo_warning
						exit 0
					fi
				fi
				boot_mesg "Starting tvheadend..." 
				/usr/bin/tvheadend -u nobody -g video -f -c /etc/tvheadend
                ;;
        stop)
				if [ -e "$PIDFILE" ]
				then
					boot_mesg "Stopping tvheadend..."
					kill -9 $(cat $PIDFILE)
					rm -f $PIDFILE
				else
					boot_mesg "tvheadend is not running..."
					exit 0
				fi 
                ;;
        restart)
                $0 stop
                sleep 3
                $0 start
                ;;
		status)
                statusproc /usr/bin/tvheadend
                ;;
        *)
                echo "Usage: $0 (start|stop|restart|status)"
                exit 1
                ;;
esac

# End $rc_base/init.d/tvheadend
