#!/bin/sh
########################################################################
# Begin $rc_base/init.d/vdr
#
# Description : This is a script that starts vdr as deamon
#
# Authors     : Arne Fitzenreiter (arne@ipfire.org)
#
# Version     : 01.00
#
# Notes       :
#
########################################################################

. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
	start)
		boot_mesg "Starting Video Disk Recorder..."
		if [ "$(ps -A | grep runvdr)" != "" ]; then
		   boot_mesg "Error! Alrady run!"
		   echo_failure
		   exit 1;
		fi
		if [ ! -e /dev/dvb/adapter0/frontend0 ]; then
		   boot_mesg "Error! No DVB tuner found."
		   echo_failure
		   exit 1;
		fi	
		loadproc screen -dmS vdr /opt/vdr/bin/runvdr
		;;
		
	stop)
		boot_mesg "Stopping Video Disk Recorder..."
		killall -s KILL -w runvdr
		killproc /opt/vdr/bin/vdr
		;;

	restart)
		${0} stop
		sleep 1
		${0} start
		;;

	status)
		statusproc /opt/vdr/bin/runvdr
		statusproc /opt/vdr/bin/vdr
		;;

	*)
		echo "Usage: ${0} {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/vdr
