#!/bin/sh
########################################################################
# Begin $rc_base/init.d/vdr
#
# Description : This is a script that starts vdr as deamon
#
# Authors     : Arne Fitzenreiter (arne@ipfire.org)
#
# Version     : 01.00
#
# Notes       :
#
########################################################################

. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
	start)
		boot_mesg "Starting Video Disk Recorder..."
		cd /opt/vdr
		loadproc screen -dmS vdr /opt/vdr/bin/vdr -Pstreamdev-server
		;;
		
	stop)
		boot_mesg "Stopping Video Disk Recorder..."
		killproc /opt/vdr/bin/vdr
		;;

	restart)
		${0} stop
		sleep 1
		${0} start
		;;

	status)
		statusproc /opt/vdr/bin/vdr
		;;

	*)
		echo "Usage: ${0} {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/vdr
