#!/bin/sh
# Begin $rc_base/init.d/vnstat

. /etc/sysconfig/rc
. $rc_functions

eval $(/usr/local/bin/readhash /var/ipfire/main/settings)

if [ "$VNSTATLOG" = '' ]; then
	VNSTATLOG=/var/log/vnstat
fi

case "$1" in
	start)
		if use_ramdisk; then
			boot_mesg "Mounting vnstat ramdisk..."
			mount_ramdisk "${VNSTATLOG}"
			evaluate_retval
		fi
		;;
	stop)
		umount_ramdisk "${VNSTATLOG}"
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

# End $rc_base/init.d/vnstat
