#!/bin/bash

PROG="$1"
VER="$2"
PAK_VER="$3"
EXT=ipfire

	# Bringing the files to their right place.
	rm -rf /install/packages/package /tmp/* /packagetmp.tar
	mkdir -p /install/packages/package
	cp -f /usr/src/src/paks/$PROG/{,un}install.sh /install/packages/package
	cp -f /usr/src/src/paks/$PROG/update.sh /install/packages/package
	cp -f /usr/src/config/rootfiles/packages/$PROG /install/packages/package/ROOTFILES
	chmod 755 /install/packages/package/{,un}install.sh

	cd /    && tar --create --directory=/ --files-from=/install/packages/package/ROOTFILES --file=/packagetmp.tar --exclude='#*'
	cd /    && tar -x -C /tmp -f /packagetmp.tar
	           rm -f /packagetmp.tar
	cd /tmp && tar --create --bzip2 --verbose --file=/install/packages/package/files.tbz2 *

	cd /    && rm -rf /tmp/*
	cd /install/packages/package && cat ROOTFILES | grep -v "#" > ROOTFILES
	tar cfj ../$PROG-${VER}_$PAK_VER.$EXT files.tbz2 install.sh uninstall.sh update.sh ROOTFILES
	
	rm -rf /install/packages/package
	exit 0
