#!/bin/bash
############################################################################
#                                                                          #
# This file is part of the IPFire Firewall.                                #
#                                                                          #
# IPFire is free software; you can redistribute it and/or modify           #
# it under the terms of the GNU General Public License as published by     #
# the Free Software Foundation; either version 2 of the License, or        #
# (at your option) any later version.                                      #
#                                                                          #
# IPFire is distributed in the hope that it will be useful,                #
# but WITHOUT ANY WARRANTY; without even the implied warranty of           #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
# GNU General Public License for more details.                             #
#                                                                          #
# You should have received a copy of the GNU General Public License        #
# along with IPFire; if not, write to the Free Software                    #
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA #
#                                                                          #
# Copyright (C) 2014 IPFire Team <info@ipfire.org>                         #
#                                                                          #
############################################################################

# This script checks if a daylight saving time transition
# has just happened and will run the given command.

HOUR_NOW=$(date "+%H")
HOUR_THEN=$(date --date="1 hour ago" "+%H")

# We expect that the result in HOUR_THEN is HOUR_NOW - 1
HOUR_EXPECTED=$(( ${HOUR_NOW} - 1 ))

if [ "${HOUR_EXPECTED}" -eq "${HOUR_THEN}" ]; then
	exit 0
fi

$@
