#!/bin/sh
#
# IPCop CGIs
#
# This file is part of the IPCop Project
# 
# This code is distributed under the terms of the GPL
#
# (c) Eric Oberlander June 2002
#
# /usr/local/bin/timecheck

if [ -e /var/ipfire/time/enable ]; then
	if [ $(cat /var/ipfire/time/settings | grep period) ] && [ -e /var/ipfire/time/counter ]; then
		if [ $(cat /var/ipfire/time/counter) -gt 0 ]; then
			echo $(($(cat /var/ipfire/time/counter)-5)) > /var/ipfire/time/counter
		else
			touch /var/ipfire/time/settimenow
			rm -f /var/ipfire/time/counter
		fi
	else
		# EAO added 2003-08-14 for v1.3.1
		# if settings are restored from a backup
		# /var/ipfire/time/counter will not exist
		if [ $(cat /var/ipfire/time/settings | grep periodic) ]; then
			touch /var/ipfire/time/settimenow
		fi
	fi

	if [ -e /var/ipfire/time/settimenow ]; then
		if 	[ -e /var/ipfire/time/settime.conf ]; then
			/usr/local/bin/settime $(cat /var/ipfire/time/settime.conf)
		fi
	fi
fi		
