# Persian (fa) Data File 
#
# This file is part of the IPCop Firewall.
# 
# IPCop is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# IPCop is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with IPCop; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
# 
# (c) The SmoothWall Team
# 
# IPCop translation
# Copyright (c) 2006 A T Khalilian, Ali Tajik 
#

%tr = ( 
%tr, 
 
'a ca certificate with this name already exists' => 'مرکز اعتبار نامه دیجیتالی با این نام هم اکنون موجود است', 
'a connection with this name already exists' => 'connection با این نام هم اکنون موجود است', 
'access allowed' => ' دسترسی اجازه داده شد از :', 
'add' => 'افزودن', 
'add a host' => 'افزودن هاست', 
'add a new rule' => 'افزودن قاعده جدید :', 
'add device' => 'افزودن دستگاه', 
'add network' => 'اضافه کردن شبکه ', 
'add new alias' => 'افزودن نام مستعار :', 
'add service' => 'افزودن سرویس', 
'added from dhcp lease list' => 'لیست آدرسهای  موقتی (DHCP lease) افزوده شد.', 
'admin user password has been changed' => 'کلمه رمز مدیریت تغییر یافت .', 
'administrator user password' => 'کلمه رمز مدیر', 
'adsl settings' => 'تنظیمات ADSL', 
'advanced' => 'پیشرفته', 
'again' => 'دوباره', 
'all' => 'همه', 
'all interfaces' => 'تمام  کارتهای واسطه (Interface)', 
'all updates installed' => 'تمام بسته های بروز رسانی نصب گردید', 
'and' => 'و', 
'april' => 'اوریل', 
'archive not exist' => 'تنظیمات آرشیو موجود نمی باشد', 
'are you sure' => 'آیا شما اطمینان دارید؟', 
'arp table entries' => 'ورود جدول  ARP :', 
'authentication' => 'تصدیق', 
'automatic' => 'خودکار', 
'available updates' => 'بسته های به روزرسانی  در دسترس :', 
'average' => 'میانگین', 
'back' => 'عقب', 
'backup' => 'پشتیبان ', 
'backup configuration' => 'تنظیمات پشتیبان گیری :', 
'blue' => 'آبی', 
'blue access' => 'دسترسی ناحیه آبی', 
'blue interface' => 'واسط ناحیه آبی', 
'ca certificate' => 'مراکز صدور گواهی اعتباری دیجیتال', 
'ca name' => 'نام مراکز گواهی اعتباری', 
'cancel' => 'لغو', 
'cant change certificates' => 'تغییر گواهینامه ها مقدور نمی باشد.', 
'certificate authorities' => 'گواهینامه اعتباری دیجیتال', 
'chain' => 'Chain', 
'change passwords' => 'تغییر کلمه های رمز', 
'city' => 'شهر', 
'click to disable' => 'فعال (برای غیر فعال کردن کلیک کنید )', 
'click to enable' => 'غیرفعال (برای فعال کردن کلیک کنید )', 
'connected' => 'اتصال برقرار شده', 
'connecting' => 'در حال برقراری اتصال...', 
'connection' => 'اتصال', 
'connection debugging' => 'اشکال زدایی اتصال', 
'connection status and controlc' => 'کنترل و وضعیت اتصال :', 
'connection tracking' => 'پیگیری اتصال IPTables :', 
'connection type' => 'نوع اتصال', 
'connections' => 'اتصال ها ', 
'country' => 'کشور', 
'cpu usage per' => 'میزان استفاده از پردازشگر در', 
'create' => 'ساختن', 
'date' => 'تاریخ', 
'day' => 'روز', 
'day after' => 'روز بعد', 
'day before' => 'روز قبل', 
'days' => 'روزها', 
'delete' => 'پاک کردن', 
'description' => 'شرح', 
'destination' => 'مقصد', 
'dhcp server' => 'DHCP Server', 
'disk usage' => 'میزلن مصرف دیسک :', 
'display' => 'نمایش', 
'display hostname in window title' => 'نمایش نام میزبان در بالای پنجره', 
'dmz' => 'DMZ', 
'domain' => 'دامنه', 
'domain name' => 'نام دامنه', 
'duplicate ip' => 'آدرس ای پی وارد شده تکراری می باشد.', 
'duplicate mac' => 'آدرس فیزیکی (مک) وارد شده تکراری می باشد.', 
'duplicate name' => 'نام مورد نظر قبلا استفاده شده , لطفا نام دیگری انتخاب نمائبد.', 
'edit' => 'ویرایش', 
'edit device' => 'ویرایش سرویس', 
'edit hosts' => 'ویرایش میزبانان', 
'edit network' => 'ویرایش شبکه', 
'edit service' => 'ویرایش سرویس', 
'empty' => 'خالی', 
'encapsulation' => 'بسته بندی', 
'encrypted' => 'رمزنگاری شده', 
'external access' => 'دسترسی خارجی', 
'external access configuration' => 'تنظیمات دسترسی خارجی', 
'february' => 'فوریه', 
'firewall' => 'دیوار آتش', 
'firmware' => 'Firmware', 
'free' => 'آزاد', 
'free memory' => 'حافظه آزاد', 
'invert' => 'معکوس', 
'ip address in use' => 'آدرس IP مورد نظر در حال استفاده می باشد.', 
'isdn' => 'ISDN', 
'isdn settings' => 'تنظیمات اضافی ISDN :', 
'kernel version' => 'نگارش هسته مرکزی :', 
'lan' => 'شبکه محلی', 
'languagepurpose' => 'زبان مورد نظر خود را انتخاب کنید :', 
'line' => 'خط', 
'main page' => 'صفحه اصلی', 
'manual control and status' => 'کنترل دستی و وضعیت :', 
'manually' => ' به صورت دستی', 
'max size' => 'حداکثر اندازه به کیلو بایت :', 
'may' => 'may', 
'memory' => 'حافظه :', 
'modem' => 'modem', 
'monday' => 'دوشنبه', 
'month' => 'ماه', 
'months' => 'ماه ها', 
'name' => 'نام', 
'name is invalid' => 'نام دارای اعتبار نمی باشد', 
'network' => 'شبکه', 
'network added' => 'شبکه افزوده شد', 
'networks settings' => 'دیوار آتش - تنظیمات شبکه', 
'next address' => 'آدرس بعدی', 
'no' => 'نه', 
'orange' => 'نارنجی', 
'other countries' => 'کشورهای دیگر', 
'password' => 'کلمه رمز', 
'port' => 'پورت', 
'port forwarding configuration' => 'تنظیمات  انتقال پورت به پورت دیگر', 
'ports' => 'پورت ها', 
'priority' => 'اولویت', 
'protocol' => 'پروتکل', 
'reboot' => 'بارگذاری مجدد', 
'rebooting ipcop' => 'بارگذاری مجدد IPCop', 
'references' => 'منابع', 
'refresh' => 'refresh', 
'remove' => 'remove', 
'restart' => 'راه اندازی مجدد', 
'save' => 'ذخیره', 
'seconds' => 'ثانیه ها', 
'september' => 'سپتامبر', 
'service' => 'سرویس', 
'settings' => 'تنظیمات', 
'show ca certificate' => 'نمایش مراکز گواهی اعتباری دیجیتال', 
'show host certificate' => 'نمایش گواهی اعتبار میزبان', 
'size' => 'اندازه', 
'sort ascending' => 'مرتب کردن صعودی', 
'successfully refreshed updates list' => 'بازفراخوانی لیست بسته های بروزرسانی با موفقیت انجام شد', 
'sunday' => 'یکشنبه', 
'swap' => 'Swap', 
'system cpu' => 'پردازشگر سیستم', 
'system cpu usage' => 'مصرف پردازشگر سیستم', 
'system graphs' => 'نمودار های سیستم', 
'system log viewer' => ' ناظر وقایع ثبت شده سیستم', 
'there are updates' => 'برای سیستم شما بسته های بروزرسانی  یافت شده است , برای اطلاعات بیشتر قسمت به روزرسانی را مشاهده نمائید.', 
'thursday' => 'پنج شنبه', 
'time' => 'زمان', 
'time server' => 'Time Server', 
'title' => 'عنوان', 
'transfer limits' => 'محدودیتهای انتقال', 
'transparent on' => 'فعالیت نا محسوس ( پشت پرده )  روشن', 
'tuesday' => 'سه شنبه', 
'type' => 'نوع', 
'unknown' => 'نا مشخص', 
'update' => 'به روزرسانی', 
'updates' => 'بسته های به روزرسانی', 
'updates installed' => 'بسته های به روزرسانی نصب گردید', 
'upload file' => 'ارسال فایل', 
'use ipcop red ip' => 'آدرسهای کلاس قرمز استفاده شده در فایروال در حین ارتباط', 
'used' => 'مصرف شده', 
'used memory' => 'حافظه مصرف شده', 
'user cpu' => 'پردازشگر کاربر', 
'user cpu usage' => 'میزان  استفاده کاربر از پردازشگر', 
'username' => 'نام کاربری :', 
'users email' => 'آدرس پست الکترونیکی کاربران', 
'users fullname or system hostname' => 'نام کامل کاربران یا نام سیستم ', 
'warning messages' => 'پیغام های خطا', 
'web hits' => 'تعداد کل  سایتهای  نتیجه شده بر اساس معیارهای انتخابی برای ', 
'web proxy' => 'پروکسی وب', 
'web proxy configuration' => 'تنظیمات پروکسی وب', 
'web server' => 'سرویس دهنده وب', 
'website' => 'سایت وب', 
'wednesday' => 'چهارشنبه', 
'week' => 'هفته', 
'weeks' => 'هفته ها', 
'wireless' => 'بی سیم', 
'wireless config added' => 'تنظیمات  بی سیم افزوده شد', 
'wireless config changed' => 'تنظیمات بی سیم تغییر یافت', 
'wireless configuration' => 'تنظیمات بی سیم', 
'year' => 'سال', 
'yes' => 'بله', 
'your e-mail' => 'شما e-mail', 
 
); 
 