#!/bin/bash

# Get the GeoIP database if no one exists yet

database_exists() {
	local file
	for file in /usr/share/xt_geoip/*.iv4; do
		[ -e "${file}" ] && return 0
	done

	# Does not exist
	return 1
}

# Download ruleset if none has been found.
if ! database_exists; then
	/usr/local/bin/xt_geoip_update >/dev/null 2>&1 &
fi

exit 0
