#!/bin/bash

. /etc/sysconfig/rc
. ${rc_functions}

get() {
	local file="${1}"

	wget -qO - "http://169.254.169.254/latest/meta-data/${file}"
}

to_address() {
	local n="${1}"

	local o1=$(( (n & 0xff000000) >> 24 ))
	local o2=$(( (n & 0xff0000) >> 16 ))
	local o3=$(( (n & 0xff00) >> 8 ))
	local o4=$(( (n & 0xff) ))

	printf "%d.%d.%d.%d\n" "${o1}" "${o2}" "${o3}" "${o4}"
}

to_integer() {
	local address="${1}"

	local integer=0

	local i
	for i in ${address//\./ }; do
		integer=$(( (integer << 8) + i ))
	done

	printf "%d\n" "${integer}"
}

prefix2netmask() {
	local prefix=${1}

	local zeros=$(( 32 - prefix ))
	local netmask=0

	local i
	for (( i=0; i<${zeros}; i++ )); do
		netmask=$(( (netmask << 1) ^ 1 ))
	done

	to_address "$(( netmask ^ 0xffffffff ))"
}

find_interface() {
	local mac="${1}"

	local path
	for path in /sys/class/net/*; do
		local address="$(<${path}/address)"

		if [ "${mac}" = "${address}" ]; then
			basename "${path}"
			return 0
		fi
	done

	return 1
}

import_aws_configuration() {
	local instance_id="$(get instance-id)"

	boot_mesg "Importing AWS configuration for instance ${instance_id}..."

	# Store instance ID
	echo "${instance_id}" > /var/run/aws-instance-id

	# Initialise system settings
	local hostname=$(get local-hostname)

	# Set hostname
	if ! grep -q "^HOSTNAME=" /var/ipfire/main/settings; then
		echo "HOSTNAME=${hostname%%.*}" >> /var/ipfire/main/settings
	fi

	# Set domainname
	if ! grep -q "^DOMAINNAME=" /var/ipfire/main/settings; then
		echo "DOMAINNAME=${hostname#*.}" >> /var/ipfire/main/settings
	fi

	# Create setup user
	if ! getent passwd setup &>/dev/null; then
		useradd -r setup -s /usr/bin/run-setup -g nobody -m
	fi

	# Import SSH keys
	local user
	for user in /root /home/setup; do
		local line
		for line in $(get "public-keys/"); do
			local key_no="${line%=*}"

			local key="$(get public-keys/${key_no}/openssh-key)"
			if [ -n "${key}" ] && ! grep -q "^${key}$" "${user}/.ssh/authorized_keys" 2>/dev/null; then
				mkdir -p "${user}/.ssh"
				chmod 700 "${user}/.ssh"

				echo "${key}" >> "${user}/.ssh/authorized_keys"
				chmod 600 "${user}/.ssh/authorized_keys"
			fi
		done
	done

	# Import any DNS server settings
	eval $(/usr/local/bin/readhash <(grep -E "^DNS([0-9])=" /var/ipfire/ethernet/settings 2>/dev/null))

	# Import network configuration
	# After this, no network connectivity will be available from this script due to the
	# renaming of the network interfaces for which they have to be shut down
	local config_type=1
	: > /var/ipfire/ethernet/settings

	local mac
	for mac in $(get network/interfaces/macs/); do
		# Remove trailing slash
		mac="${mac//\//}"

		local device_number="$(get "network/interfaces/macs/${mac}/device-number")"
		local interface_id="$(get "network/interfaces/macs/${mac}/interface-id")"

		# First IPv4 address
		local ipv4_address="$(get "network/interfaces/macs/${mac}/local-ipv4s" | head -n1)"
		local ipv4_address_num="$(to_integer "${ipv4_address}")"

		# Get VPC subnet
		local vpc="$(get "network/interfaces/macs/${mac}/vpc-ipv4-cidr-block")"
		local vpc_netaddress="${vpc%/*}"
		local vpc_netaddress_num="$(to_integer "${vpc_netaddress}")"

		# Get subnet size
		local subnet="$(get "network/interfaces/macs/${mac}/subnet-ipv4-cidr-block")"

		local prefix="${subnet#*/}"
		local netmask="$(prefix2netmask "${prefix}")"
		local netmask_num="$(to_integer "${netmask}")"

		# Calculate the network and broadcast addresses
		local netaddress="${subnet%/*}"
		local netaddress_num="$(to_integer "${netaddress}")"
		local broadcast="$(to_address $(( ipv4_address_num | (0xffffffff ^ netmask_num) )))"

		case "${device_number}" in
			# RED
			0)
				local interface_name="red0"

				# The gateway is always the first IP address in the subnet
				local gateway="$(to_address $(( netaddress_num + 1 )))"

				# The AWS internal DNS service is available on the second IP address of the VPC
				local dns1="$(to_address $(( vpc_netaddress_num + 2 )))"
				local dns2=

				(
					echo "RED_TYPE=STATIC"
					echo "RED_DEV=${interface_name}"
					echo "RED_MACADDR=${mac}"
					echo "RED_DESCRIPTION='${interface_id}'"
					echo "RED_ADDRESS=${ipv4_address}"
					echo "RED_NETMASK=${netmask}"
					echo "RED_NETADDRESS=${netaddress}"
					echo "RED_BROADCAST=${broadcast}"
					echo "DEFAULT_GATEWAY=${gateway}"
					echo "DNS1=${DNS1:-${dns1}}"
					echo "DNS2=${DNS2:-${dns2}}"
				) >> /var/ipfire/ethernet/settings

				# Import aliases for RED
				for alias in $(get "network/interfaces/macs/${mac}/local-ipv4s" | tail -n +2); do
					echo "${alias},on,"
				done > /var/ipfire/ethernet/aliases
				;;

			# GREEN
			1)
				local interface_name="green0"

				(
					echo "GREEN_DEV=${interface_name}"
					echo "GREEN_MACADDR=${mac}"
					echo "GREEN_DESCRIPTION='${interface_id}'"
					echo "GREEN_ADDRESS=${ipv4_address}"
					echo "GREEN_NETMASK=${netmask}"
					echo "GREEN_NETADDRESS=${netaddress}"
					echo "GREEN_BROADCAST=${broadcast}"
				) >> /var/ipfire/ethernet/settings
				;;

			# ORANGE
			2)
				local interface_name="orange0"
				config_type=2

				(
					echo "ORANGE_DEV=${interface_name}"
					echo "ORANGE_MACADDR=${mac}"
					echo "ORANGE_DESCRIPTION='${interface_id}'"
					echo "ORANGE_ADDRESS=${ipv4_address}"
					echo "ORANGE_NETMASK=${netmask}"
					echo "ORANGE_NETADDRESS=${netaddress}"
					echo "ORANGE_BROADCAST=${broadcast}"
				) >> /var/ipfire/ethernet/settings
				;;
		esac

		# Rename interface
		local interface="$(find_interface "${mac}")"

		if [ -n "${interface}" ] && [ -n "${interface_name}" ] && [ "${interface}" != "${interface_name}" ]; then
			ip link set "${interface}" down
			ip link set "${interface}" name "${interface_name}"
		fi
	done

	# Save CONFIG_TYPE
	echo "CONFIG_TYPE=${config_type}" >> /var/ipfire/ethernet/settings

	# Actions performed only on the very first start
	if [ ! -e "/var/ipfire/main/firstsetup_ok" ]; then
		# Enable SSH
		sed -e "s/ENABLE_SSH=.*/ENABLE_SSH=on/g" -i /var/ipfire/remote/settings

		# Enable SSH key authentication
		sed -e "s/^ENABLE_SSH_KEYS=.*/ENABLE_SSH_KEYS=on/" -i /var/ipfire/remote/settings

		# Apply SSH settings
		/usr/local/bin/sshctrl

		# Mark SSH to start immediately (but not right now)
		touch /var/ipfire/remote/enablessh
		chown nobody:nobody /var/ipfire/remote/enablessh

		# Firewall rules for SSH and WEBIF
		(
			echo "1,ACCEPT,INPUTFW,ON,std_net_src,ALL,ipfire,RED1,,TCP,,,ON,,,cust_srv,SSH,,,,,,,,,,,00:00,00:00,,AUTO,,dnat,,,,,second"
			echo "2,ACCEPT,INPUTFW,ON,std_net_src,ALL,ipfire,RED1,,TCP,,,ON,,,TGT_PORT,444,,,,,,,,,,,00:00,00:00,,AUTO,,dnat,,,,,second"
		) >> /var/ipfire/firewall/input

		# This script has now completed the first steps of setup
		touch /var/ipfire/main/firstsetup_ok
	fi

	# All done
	echo_ok
}

case "${reason}" in
	PREINIT)
		# Bring up the interface
		ip link set "${interface}" up
		;;

	BOUND|RENEW|REBIND|REBOOT)
		# Remove any previous IP addresses
		ip addr flush dev "${interface}"

		# Add (or re-add) the new IP address
		ip addr add "${new_ip_address}/${new_subnet_mask}" dev "${interface}"

		# Add the default route
		ip route add default via "${new_routers}"

		# Import AWS configuration
		import_aws_configuration
		;;

	EXPIRE|FAIL|RELEASE|STOP)
		# Remove all IP addresses
		ip addr flush dev "${interface}"
		;;

	*)
		echo "Unhandled reason: ${reason}" >&2
		exit 2
		;;
esac

# Terminate
exit 0
