#!/bin/sh

eval $(/usr/local/bin/readhash /var/ipfire/forward/settings)
eval $(/usr/local/bin/readhash /var/ipfire/optionsfw/settings)

iptables -F POLICYFWD
iptables -F POLICYOUT


if [ "$POLICY" == "MODE1" ]; then
		if [ "$FWPOLICY" == "REJECT" ]; then
			if [ "$DROPFORWARD" == "on" ]; then
				/sbin/iptables -A POLICYFWD -m limit --limit 10/minute -j LOG --log-prefix "REJECT_FORWARD"
			fi
			/sbin/iptables -A POLICYFWD -j REJECT --reject-with icmp-host-unreachable -m comment --comment "DROP_FORWARD"
		fi
		if [ "$FWPOLICY" == "DROP" ]; then
			if [ "$DROPFORWARD" == "on" ]; then
				/sbin/iptables -A POLICYFWD -m limit --limit 10/minute -j LOG --log-prefix "DROP_FORWARD"
			fi
			/sbin/iptables -A POLICYFWD -j DROP -m comment --comment "DROP_FORWARD"
		fi
fi
if [ "$POLICY1" == "MODE1" ]; then
	/sbin/iptables -I OUTGOINGFW 1 -m state --state ESTABLISHED,RELATED -j ACCEPT
		if [ "$FWPOLICY1" == "REJECT" ]; then
			if [ "$DROPOUTGOING" == "on" ]; then
				/sbin/iptables -A POLICYOUT -m limit --limit 10/minute -j LOG --log-prefix "REJECT_OUTPUT"
			fi
				/sbin/iptables -A POLICYOUT -j REJECT --reject-with icmp-host-unreachable -m comment --comment "DROP_OUTPUT"
		fi
		if [ "$FWPOLICY1" == "DROP" ]; then
			if [ "$DROPOUTGOING" == "on" ]; then
				/sbin/iptables -A POLICYOUT -m limit --limit 10/minute -j LOG --log-prefix "DROP_OUTPUT"
			fi
				/sbin/iptables -A POLICYOUT -j DROP -m comment --comment "DROP_OUTPUT"
		fi
fi

