#!/bin/sh
if [ ! -e /etc/ssh/ssh_host_key ]; then
	echo "Generating SSH RSA1 key.  This may take several minutes."
	/usr/bin/ssh-keygen -t rsa1 -f /etc/ssh/ssh_host_key -N ""
fi
if [ ! -e /etc/ssh/ssh_host_rsa_key ]; then
	echo "Generating SSH RSA key.  This may take several minutes."
	/usr/bin/ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ""
fi
if [ ! -e /etc/ssh/ssh_host_dsa_key ]; then
	echo "Generating SSH DSA key.  This may take several minutes."
	/usr/bin/ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N "" 
fi
