deps_config := \
	target/generic/Config.in \
	target/device/jp/Config.in \
	target/device/Sharp/Config.in \
	target/device/Via/Config.in \
	target/device/AMD/Config.in \
	target/device/Hitachi/Config.in \
	target/device/Soekris/Config.in \
	target/device/Config.in \
	target/powerpc/yaboot/Config.in \
	target/x86/syslinux/Config.in \
	target/x86/grub/Config.in \
	target/iso9660/Config.in \
	target/tar/Config.in \
	target/squashfs/Config.in \
	target/jffs2/Config.in \
	target/ext2/Config.in \
	target/cloop/Config.in \
	target/cramfs/Config.in \
	target/Config.in \
	package/zlib/Config.in \
	package/xorg/Config.in \
	package/xfsprogs/Config.in \
	package/wireless-tools/Config.in \
	package/wipe/Config.in \
	package/which/Config.in \
	package/wget/Config.in \
	package/vtun/Config.in \
	package/valgrind/Config.in \
	package/util-linux/Config.in \
	package/usbutils/Config.in \
	package/uemacs/Config.in \
	package/udhcp/Config.in \
	package/udev/Config.in \
	package/ttcp/Config.in \
	package/tn5250/Config.in \
	package/tinyx/Config.in \
	package/tinylogin/Config.in \
	package/thttpd/Config.in \
	package/tftpd/Config.in \
	package/tcpdump/Config.in \
	package/tcl/Config.in \
	package/sysvinit/Config.in \
	package/sysklogd/Config.in \
	package/sudo/Config.in \
	package/strace/Config.in \
	package/sqlite/Config.in \
	package/socat/Config.in \
	package/smartmontools/Config.in \
	package/slang/Config.in \
	package/sfdisk/Config.in \
	package/sdl/Config.in \
	package/rxvt/Config.in \
	package/ruby/Config.in \
	package/rsync/Config.in \
	package/readline/Config.in \
	package/raidtools/Config.in \
	package/qte/Config.in \
	package/python/Config.in \
	package/psmisc/Config.in \
	package/procps/Config.in \
	package/pppd/Config.in \
	package/portmap/Config.in \
	package/portage/Config.in \
	package/pkgconfig/Config.in \
	package/pcmcia/Config.in \
	package/pciutils/Config.in \
	package/openvpn/Config.in \
	package/openssl/Config.in \
	package/openssh/Config.in \
	package/openntpd/Config.in \
	package/ntp/Config.in \
	package/newt/Config.in \
	package/netsnmp/Config.in \
	package/netkittelnet/Config.in \
	package/netkitbase/Config.in \
	package/ncurses/Config.in \
	package/nbd/Config.in \
	package/nano/Config.in \
	package/mtd/Config.in \
	package/mrouted/Config.in \
	package/mpg123/Config.in \
	package/modutils/Config.in \
	package/module-init-tools/Config.in \
	package/mkdosfs/Config.in \
	package/microwin/Config.in \
	package/microperl/Config.in \
	package/microcom/Config.in \
	package/memtester/Config.in \
	package/mdadm/Config.in \
	package/m4/Config.in \
	package/lzma/Config.in \
	package/lzo/Config.in \
	package/lvm2/Config.in \
	package/ltt/Config.in \
	package/ltrace/Config.in \
	package/ltp-testsuite/Config.in \
	package/lsof/Config.in \
	package/lrzsz/Config.in \
	package/links/Config.in \
	package/lighttpd/Config.in \
	package/libusb/Config.in \
	package/libtool/Config.in \
	package/libsysfs/Config.in \
	package/libpng/Config.in \
	package/libpcap/Config.in \
	package/libmad/Config.in \
	package/libgtk12/Config.in \
	package/libglib12/Config.in \
	package/libfloat/Config.in \
	package/libelf/Config.in \
	package/libcgicc/Config.in \
	package/libcgi/Config.in \
	package/less/Config.in \
	package/jpeg/Config.in \
	package/iptables/Config.in \
	package/ipsec-tools/Config.in \
	package/iproute2/Config.in \
	package/iostat/Config.in \
	package/hotplug/Config.in \
	package/hostap/Config.in \
	package/hdparm/Config.in \
	package/haserl/Config.in \
	package/gzip/Config.in \
	package/gettext/Config.in \
	package/freetype/Config.in \
	package/file/Config.in \
	package/fakeroot/Config.in \
	package/e2fsprogs/Config.in \
	package/expat/Config.in \
	package/ethtool/Config.in \
	package/dropbear/Config.in \
	package/dnsmasq/Config.in \
	package/dmraid/Config.in \
	package/dm/Config.in \
	package/distcc/Config.in \
	package/directfb/Config.in \
	package/dillo/Config.in \
	package/dialog/Config.in \
	package/dhcp/Config.in \
	package/customize/Config.in \
	package/bridge/Config.in \
	package/boa/Config.in \
	package/bison/Config.in \
	package/bind/Config.in \
	package/berkeleydb/Config.in \
	package/automake/Config.in \
	package/autoconf/Config.in \
	package/at/Config.in \
	package/asterisk/Config.in \
	package/acpid/Config.in \
	package/tar/Config.in \
	package/sed/Config.in \
	package/patch/Config.in \
	package/make/Config.in \
	package/grep/Config.in \
	toolchain/ccache/Config.in.2 \
	toolchain/gcc/Config.in.2 \
	package/gawk/Config.in \
	package/flex/Config.in \
	package/findutils/Config.in \
	package/ed/Config.in \
	package/diffutils/Config.in \
	package/coreutils/Config.in \
	package/bzip2/Config.in \
	package/bash/Config.in \
	package/busybox/Config.in \
	package/Config.in \
	toolchain/sstrip/Config.in \
	toolchain/mklibs/Config.in \
	toolchain/elf2flt/Config.in \
	toolchain/gdb/Config.in \
	toolchain/ccache/Config.in \
	toolchain/gcc/Config.in \
	toolchain/binutils/Config.in \
	toolchain/uClibc/Config.in \
	toolchain/kernel-headers/Config.in \
	toolchain/Config.in \
	Config.in

.config include/config.h: $(deps_config)

$(deps_config):
